spring:
  application:
    name: test-graphql

server:
  http2:
    enabled: true

graphql:
  servlet:
    maxQueryDepth: 3
  playground:
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
#    enabled: false